import re
import os

def fix_text(text):
    text = text.replace("Constitucin", "Constitución")
    text = text.replace("Nacin", "Nación")
    text = text.replace("jurisdiccin", "jurisdicción")
    text = text.replace("accin", "acción")
    text = text.replace("educacin", "educación")
    text = text.replace("relacin", "relación")
    text = text.replace("funcin", "función")
    text = text.replace("organizacin", "organización")
    text = text.replace("poltica", "política")
    text = text.replace("jurdica", "jurídica")
    text = text.replace("garanta", "garantía")
    text = text.replace("economa", "economía")
    text = text.replace("Pblico", "Público")
    text = text.replace("artculo", "artículo")
    text = text.replace("ms", "más")
    text = text.replace("mbito", "ámbito")
    text = text.replace("ttulo", "título")
    text = text.replace("proteccin", "protección")
    text = text.replace("violacin", "violación")
    text = text.replace("aplicacin", "aplicación")
    text = text.replace("resolucin", "resolución")
    text = text.replace("disposicin", "disposición")
    text = text.replace("situacin", "situación")
    text = text.replace("condicin", "condición")
    text = text.replace("obligacin", "obligación")
    text = text.replace("evaluacin", "evaluación")
    text = text.replace("gestin", "gestión")
    text = text.replace("direccin", "dirección")
    text = text.replace("investigacin", "investigación")
    text = text.replace("intervencin", "intervención")
    text = text.replace("actuacin", "actuación")
    text = text.replace("sancin", "sanción")
    text = text.replace("excepcin", "excepción")
    text = text.replace("decisin", "decisión")
    text = text.replace("discusin", "discusión")
    text = text.replace("prisin", "prisión")
    text = text.replace("comisin", "comisión")
    text = text.replace("revisin", "revisión")
    text = text.replace("cuestin", "cuestión")
    text = text.replace("peticin", "petición")
    text = text.replace("exhibicin", "exhibición")
    text = text.replace("designacin", "designación")
    text = text.replace("eleccin", "elección")
    text = text.replace("creacin", "creación")
    text = text.replace("extincin", "extinción")
    text = text.replace("modificacin", "modificación")
    text = text.replace("declaracin", "declaración")
    text = text.replace("restitucin", "restitución")
    text = text.replace("reparacin", "reparación")
    text = text.replace("filiacin", "filiación")
    text = text.replace("adopcin", "adopción")
    text = text.replace("convencin", "convención")
    text = text.replace("Nacin", "Nación")
    text = text.replace("Garantas", "Garantías")
    text = text.replace("Cmara", "Cámara")
    text = text.replace("Repblica", "República")
    text = text.replace("nica", "única")
    text = text.replace("ltimo", "último")
    text = text.replace("slo", "sólo")
    text = text.replace("segn", "según")
    text = text.replace("as", "así")
    text = text.replace("all", "allí")
    text = text.replace("aqu", "aquí")
    text = text.replace("qu", "qué")
    text = text.replace("quin", "quién")
    text = text.replace("cul", "cuál")
    text = text.replace("cmo", "cómo")
    text = text.replace("cundo", "cuándo")
    text = text.replace("dnde", "dónde")
    text = text.replace("", "ó")
    text = text.replace("?", "í")
    text = text.replace("ǭ", "á")
    text = text.replace("Ǹ", "é")
    text = text.replace("ǧ", "ú")
    return text

for file in ["src/data/texts.ts", "src/data/topics.ts"]:
    with open(file, "r", encoding="utf-8") as f:
        content = f.read()
    with open(file, "w", encoding="utf-8") as f:
        f.write(fix_text(content))
